
import { Warranty, WarrantyClaim, WarrantyMetrics } from './types';

export const mockWarranties: Warranty[] = [
  {
    id: 'W-1001',
    assetId: 'A-1234',
    assetName: 'UPS System 48kVA',
    assetType: 'Power Equipment',
    startDate: '2023-01-15',
    expirationDate: '2026-01-15',
    coverageType: 'Full',
    provider: 'APC by Schneider Electric',
    providerContact: 'support@apc.com',
    status: 'Active',
    documents: ['warranty_certificate.pdf', 'terms_conditions.pdf'],
    notes: 'Extended warranty purchased with 24/7 support'
  },
  {
    id: 'W-1002',
    assetId: 'A-1235',
    assetName: 'Cooling Unit #3',
    assetType: 'HVAC',
    startDate: '2022-06-20',
    expirationDate: '2023-12-20',
    coverageType: 'Parts',
    provider: 'Carrier',
    providerContact: 'service@carrier.com',
    status: 'Expiring Soon',
    documents: ['warranty_card.pdf'],
  },
  {
    id: 'W-1003',
    assetId: 'A-1236',
    assetName: 'Server Rack PDU',
    assetType: 'Power Distribution',
    startDate: '2021-09-10',
    expirationDate: '2023-09-10',
    coverageType: 'Replacement',
    provider: 'Eaton',
    providerContact: 'eaton_support@eaton.com',
    status: 'Expired',
    documents: ['warranty_policy.pdf'],
  },
  {
    id: 'W-1004',
    assetId: 'A-1237',
    assetName: 'Network Switch Core',
    assetType: 'Network Equipment',
    startDate: '2023-03-15',
    expirationDate: '2028-03-15',
    coverageType: 'Service',
    provider: 'Cisco',
    providerContact: 'cisco_enterprise@cisco.com',
    status: 'Active',
    documents: ['warranty_agreement.pdf', 'service_level_agreement.pdf'],
    notes: 'Includes quarterly preventive maintenance'
  },
  {
    id: 'W-1005',
    assetId: 'A-1238',
    assetName: 'Fire Suppression System',
    assetType: 'Safety Equipment',
    startDate: '2022-11-05',
    expirationDate: '2027-11-05',
    coverageType: 'Full',
    provider: 'FirePro Systems',
    providerContact: 'support@firepro.com',
    status: 'Active',
    documents: ['warranty_certificate.pdf', 'maintenance_schedule.pdf'],
  },
  {
    id: 'W-1006',
    assetId: 'A-1239',
    assetName: 'Backup Generator 500kW',
    assetType: 'Power Equipment',
    startDate: '2021-05-15',
    expirationDate: '2024-05-15',
    coverageType: 'Repair',
    provider: 'Cummins',
    providerContact: 'service@cummins.com',
    status: 'Active',
    documents: ['warranty_details.pdf'],
    notes: 'Annual service required to maintain warranty'
  },
  {
    id: 'W-1007',
    assetId: 'A-1240',
    assetName: 'CRAC Unit #2',
    assetType: 'HVAC',
    startDate: '2020-08-20',
    expirationDate: '2023-08-20',
    coverageType: 'Parts',
    provider: 'Vertiv',
    providerContact: 'vertiv_support@vertiv.com',
    status: 'Expired',
    documents: ['warranty_certificate.pdf'],
  },
  {
    id: 'W-1008',
    assetId: 'A-1241',
    assetName: 'SAN Storage System',
    assetType: 'Storage Equipment',
    startDate: '2023-01-10',
    expirationDate: '2026-01-10',
    coverageType: 'Full',
    provider: 'Dell EMC',
    providerContact: 'enterprise_support@dell.com',
    status: 'Active',
    documents: ['warranty_agreement.pdf', 'support_terms.pdf'],
    notes: '4-hour response time included'
  }
];

export const mockWarrantyClaims: WarrantyClaim[] = [
  {
    id: 'C-2001',
    warrantyId: 'W-1001',
    assetId: 'A-1234',
    assetName: 'UPS System 48kVA',
    dateSubmitted: '2023-06-15',
    description: 'Battery module failure detected during routine maintenance',
    documents: ['diagnostic_report.pdf', 'battery_test_results.pdf'],
    status: 'Approved',
    assignedTo: 'Sarah Chen',
    vendor: 'APC by Schneider Electric',
    estimatedValue: 3200,
    actualValue: 3100,
    resolutionDate: '2023-07-01',
    resolutionNotes: 'Full battery replacement provided under warranty'
  },
  {
    id: 'C-2002',
    warrantyId: 'W-1002',
    assetId: 'A-1235',
    assetName: 'Cooling Unit #3',
    dateSubmitted: '2023-10-10',
    description: 'Refrigerant leak detected, compressor showing signs of wear',
    documents: ['service_report.pdf', 'leak_test_images.jpg'],
    status: 'Under Review',
    assignedTo: 'Michael Rodriguez',
    vendor: 'Carrier',
    estimatedValue: 4500,
    actualValue: undefined,
    resolutionDate: undefined,
    resolutionNotes: undefined
  },
  {
    id: 'C-2003',
    warrantyId: 'W-1004',
    assetId: 'A-1237',
    assetName: 'Network Switch Core',
    dateSubmitted: '2023-05-20',
    description: 'GBIC port failure on primary network switch',
    documents: ['diagnostic_log.pdf', 'network_test_results.pdf'],
    status: 'Closed',
    assignedTo: 'James Wilson',
    vendor: 'Cisco',
    estimatedValue: 1800,
    actualValue: 1800,
    resolutionDate: '2023-06-15',
    resolutionNotes: 'Module replaced by Cisco technician'
  },
  {
    id: 'C-2004',
    warrantyId: 'W-1006',
    assetId: 'A-1239',
    assetName: 'Backup Generator 500kW',
    dateSubmitted: '2023-09-05',
    description: 'Controller malfunction during monthly test',
    documents: ['test_report.pdf', 'error_logs.pdf'],
    status: 'Submitted',
    assignedTo: 'Lisa Johnson',
    vendor: 'Cummins',
    estimatedValue: 3500,
    actualValue: undefined,
    resolutionDate: undefined,
    resolutionNotes: undefined
  },
  {
    id: 'C-2005',
    warrantyId: 'W-1008',
    assetId: 'A-1241',
    assetName: 'SAN Storage System',
    dateSubmitted: '2023-07-12',
    description: 'Disk array controller failure causing system performance issues',
    documents: ['performance_logs.pdf', 'diagnostic_report.pdf'],
    status: 'Denied',
    assignedTo: 'Ahmed Hassan',
    vendor: 'Dell EMC',
    estimatedValue: 5200,
    actualValue: 0,
    resolutionDate: '2023-08-01',
    resolutionNotes: 'Claim denied due to unauthorized modifications to the system'
  }
];

export const mockWarrantyMetrics: WarrantyMetrics = {
  activeWarranties: 65,
  expiringWarranties: 12,
  expiredWarranties: 23,
  pendingClaims: 8,
  approvedClaims: 42,
  deniedClaims: 5,
  totalSavings: 183500,
  claimSuccessRate: 89.4,
  avgResolutionDays: 12.3,
  coverageCompleteness: 78.5
};
